#docker compose para rodar a container
version: "3.7"

# serviços necessários para rodar a aplicação
services:
  app:
    build: . #. representa o diretório local
    container_name: rentax
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
# comando docker
# docker ps ->  mostra todos os containers que estão dorando
# docker ps -a -> mostra todos os constainers existentes
# docker rm id_do_container/nome_container -> remove o container
# docker start nome_container -> inicia o container
# docker stop nome_container -> para o container

# comandos docker-compose
# docker-compose up -d ->
# docker-compose down -> remove tudo que foi criado dentro do container
# docker-compose stop -> apenas para o container, mantendo os dados

# docker exec -it rentax /bin/bash -> acessa a máquina do container
# docker logs rentax -> mostra os últimos logs
# docker logs rentax -f -> fica escutando os logs do container
